fix: invisible holograms with 1.7 clients
ViaVersion/ViaRewind pull request #558
Opened 2024-12-26 16:43 UTC by blastyman

2024-12-27 19:00 UTC, FlorianMichael requested changes
This is not correct, when comparing both game source codes the type definitely has changed. Are there any errors or is the server sending per version data to the player?

2024-12-29 16:21 UTC, blastyman commented
Yes, the server is sending per version data to the player, since armor stands do not exist on 1.7 so we have to send 1.7 specific holograms (aka horse with negative age)

2024-12-29 16:25 UTC, FlorianMichael commented
Then the server is sending bad data which not would on a native client as well. Assuming the server is running 1.8, why does it even need per version data? ViaRewind should take care of entity data rewriting and emulate armor stands send by the server.

2024-12-29 16:36 UTC, blastyman commented
Because ViaRewind doesn't take proper care of it, it's broken. Otherwise we wouldn't do it

2024-12-29 17:05 UTC, FlorianMichael commented
Then it would make more sense to report it properly, but anyway you are sending wrong data to the client. This needs fixing in your server plugins instead of ViaRewind.

2024-12-29 18:32 UTC, blastyman commented
![image](https://github.com/user-attachments/assets/5ff0b3df-b53b-4e9f-8e2d-3387551cee03)

The problem still persists that ViaRewind doesn't work as intended. And I'm not going to fix it myself or hire a developer to do it as it's not my plugin. My commit fixes the issue immediately without breaking anything. Whether or not you want to merge this is up to you

2025-02-12 15:57 UTC, FlorianMichael commented
I tried the code you provided and yeah the holograms don't seem to work with that, however when I merge your code it doesn't work either and I only get exceptions complaining about invalid entity data types (as I expected). I am going to close this as I can't verify this code working and I created a issue for the problem itself: https://github.com/ViaVersion/ViaRewind/issues/563

2025-02-12 15:57 UTC, closed without merging

2025-07-25 18:56 UTC, FlorianMichael commented
The issue should be fixed now.